baseURL: "https://finlyzing.com/"
title: Finlyzing
paginate: 5
theme: hugo-PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

menu:
  main:
    - name: About
      url: /about/
      weight: 10
    - name: Posts
      url: /archive/
      weight: 20
    - name: Tags
      url: /tags/
      weight: 30
    - name: Search
      url: /search/
      weight: 40

      
outputs:
    home:
        - HTML
        - RSS
        - JSON
  
params:
    env: production
    description: "Theme PaperMod - https://github.com/mvanhuffel"
    author: Matthew Van Huffel
    ShowShareButtons: false
    ShowBreadCrumbs: true
    ShowPostNavLinks: false
    ShowCodeCopyButtons: true
    comments: true
    disableThemeToggle: true
    defaultTheme: light
    ShowReadingTime: true
    Keyword: [Blog, Data Analysis, Finance]
    showtoc: false
    tocopen: false
    DateFormat: "January 2, 2006"
    disableAnchoredHeadings: true

    assets:
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
    
    label:
        icon: "/favicon.ico"
        iconHeight: 35

    homeInfoParams:
        Title: ""
        Content: >
            This is the hopepage and blog of Matthew Van Huffel. For more about me, [**see here**](/about).
    
    socialIcons:
        - name: github
          url: "https://github.com/mvanhuffel"
        - name: linkedin
          url: "https://linkedin.com/in/matthew-vanhuffel/"
        - name: discord
          url: "https://discord.com"
        - name: email
          url: "mailto:finlyzing@gmail.com"
          
taxonomies:
    category: categories
    tag: tags
    series: series


markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
